In [1]:
import numpy as np

In [2]:
np.array([10, 20, 24, 5, 15, 50])

array([10, 20, 24,  5, 15, 50])

In [3]:
a = np.array([10, 30, 20, 4, 10, 51, 7, 4, 4, 40, 100])
a[4]

10

In [4]:
a[3:]

array([  4,  10,  51,   7,   4,   4,  40, 100])

In [5]:
a[3:7]

array([ 4, 10, 51,  7])

In [6]:
a[1::4]

array([30, 51, 40])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
type(np.ones)

function

In [16]:
np.linspace(3, 10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [18]:
b = np.array( [['x','y','z'],['a','b','e']])
print(b)
type(b)

[['x' 'y' 'z']
 ['a' 'b' 'e']]


numpy.ndarray

In [19]:
b.ndim

2

In [20]:
c = [12, 4, 10, 40, 2]

In [21]:
np.sort(c)

array([ 2,  4, 10, 12, 40])

In [22]:
cabeceras = [('nombre', 'S10'), ('edad', int)]
datos  = [ ('Juan', 10), ('Maria', 70), ('Javier', 42), ('Samuel', 15)]

In [23]:
usuarios = np.array(datos,dtype = cabeceras)

In [24]:
np.sort(usuarios, order = 'edad')

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

## Ordenar mediante arange

In [25]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
np.full((3,8), [['a'], ['b'], ['c']])

array([['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a'],
       ['b', 'b', 'b', 'b', 'b', 'b', 'b', 'b'],
       ['c', 'c', 'c', 'c', 'c', 'c', 'c', 'c']], dtype='<U1')

In [33]:
np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [37]:
np.full( (3,10), 90)

array([[90, 90, 90, 90, 90, 90, 90, 90, 90, 90],
       [90, 90, 90, 90, 90, 90, 90, 90, 90, 90],
       [90, 90, 90, 90, 90, 90, 90, 90, 90, 90]])

In [40]:
np.diag( [0, 3, 9, 10, 11, 12, 13, 14, 15])

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  9,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 12,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 13,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 14,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 15]])