# Guardar un arreglo en un archivo

In [2]:
import numpy as np

In [3]:
a = np.arange(50)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

# Guardar con Savetxt

In [4]:
np.savetxt('./ejemplo1.txt', a)

## Cargar desde un archivo

In [5]:
np.loadtxt('./ejemplo1.txt')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [6]:
# Guardamos el arreglo que cargamos en una variable
b = np.loadtxt('./ejemplo1.txt')
b

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

# Guardar el arreglo en CSV

In [7]:
# Creamos el arreglo que vamos a almacenar
a = np.random.randint(1, 10, (3, 5))
a

array([[4, 4, 4, 9, 2],
       [8, 2, 9, 2, 6],
       [7, 8, 3, 8, 1]])

In [8]:
# Guardamos el valor en formato csv
# Podemos pasarle un argumento extra para delimitar cada valor que se guarde en el archivo
np.savetxt('./ejemplo1.csv', a, delimiter=';')

## Cargar desde un archivo

In [9]:
np.loadtxt('./ejemplo1.csv', delimiter=';')


array([[4., 4., 4., 9., 2.],
       [8., 2., 9., 2., 6.],
       [7., 8., 3., 8., 1.]])

# Guardar con Save

In [10]:
arreglo = np.random.randint(1, 10, (3,5))
arreglo

array([[9, 6, 7, 4, 1],
       [1, 9, 7, 7, 9],
       [1, 5, 8, 8, 1]])

### La funcion save genera un archivo binario

In [11]:
np.save('./ejemplo2.npy', arreglo)

## Cargar el binario numpy

In [12]:
np.load('./ejemplo2.npy')

array([[9, 6, 7, 4, 1],
       [1, 9, 7, 7, 9],
       [1, 5, 8, 8, 1]])

# Guardar con SaveZ (Comprime el archivo)

In [13]:
np.savez('./ejemplo2.npz',arreglo)

## Cargar el archivo comprimido
### En este caso es necesario acceder al primer valor

In [14]:
# Cargamos el valor pero sigue comprimido
np.load('./ejemplo2.npz')

In [15]:
# Cargamos el valor pero descomprimimos el arreglo
np.load('./ejemplo2.npz')['arr_0']

array([[9, 6, 7, 4, 1],
       [1, 9, 7, 7, 9],
       [1, 5, 8, 8, 1]])

# Cargar archivos poco convencionales

In [22]:
np.genfromtxt('./paises.txt', usecols=[1, 2], skip_header=1, skip_footer=1, comments='#', delimiter=',')

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2555: character maps to <undefined>