# Formas de actualizar un arreglo con numpy

In [2]:
import numpy as np
a = np.arange(0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Cambiamos el elemento 5 por 100

In [4]:
a[5] = 100
a

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

### Cambiar elementos dentro de un rango (indices) por un numero definido

In [6]:
a[0:4] = 20
a

array([ 20,  20,  20,  20,   4, 100,   6,   7,   8,   9])

### Actualizamos mediante una lista de indices

In [8]:
a[[4, 6, 7]] = 10
a

array([ 20,  20,  20,  20,  10, 100,  10,  10,   8,   9])

### Agregar un elemento al final del arreglo creando uno nuevo

In [9]:
np.append(a, 50)

array([ 20,  20,  20,  20,  10, 100,  10,  10,   8,   9,  50])

In [10]:
a

array([ 20,  20,  20,  20,  10, 100,  10,  10,   8,   9])

### Si deseamos actualizar, lo almacenamos en el arreglo directamente

In [16]:
a = np.append(a, 50)
a

array([ 20,  20,  20,  20,  10, 100,  10,  10,   8,   9,  50,  50,  50,
        50,  50,  50])

### Eliminar un elemento del arreglo
Primero se crea un nuevo arreglo, este donde vemos que realmente eliminamos el valor que deseabamos

In [18]:
np.delete(a, 5)

array([20, 20, 20, 20, 10, 10, 10,  8,  9, 50, 50, 50, 50, 50, 50])

In [19]:
a = np.delete(a, 5)

In [20]:
a

array([20, 20, 20, 20, 10, 10, 10,  8,  9, 50, 50, 50, 50, 50, 50])