# Creacion de Arreglos

## Array
### Recibe como argumento una lista 

## Arange
### Permite generar un arreglo a partir de un rango (start, end, jump)

## Zeros One
### Permite generar un arreglo de O o 1, dependiendo cual usemos

## Full
### Llena n veces con un elemento definido

## Random Random
### Permite generar numeros aleatorios 

## Random randint
### Arreglo de numeros aleatorios dentro de un rango

Importamos la libreria con la que vamos a trabajar

In [1]:
import numpy as np

## Creacion de un arreglo usando *Arange*
 Necesitamos dos parametros, el inicio del arreglo y el final de este

In [2]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Se pueden crear arreglos con saltos definidos, pasando un tercer parametro al arange

In [3]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Creacion de un arreglo lleno de 0
Por defecto, el arreglo tiene una salida en flotante

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Podemos mostrar el arreglo de Zeros en enteros con el dtype np.int64

In [5]:
np.zeros(10, dtype=np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

## Creacion de un arreglo lleno de Unos
Por defecto, crea el arreglo en flotante

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Podemos mostrar el arreglo lleno de unos enteros

In [7]:
np.ones(10, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

## Arreglos automaticos
### Un arreglo llena 10 veces con elementos 5


In [8]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## Arreglo de elementos aleatorios
Este arreglo solo almacena a 2 numeros aleatorios pero puede hacerce mucho mas grande 

In [9]:
np.random.random(2)

array([0.75693477, 0.29317127])

Arreglo de 15 elementos aleatorios

In [10]:
np.random.random(15)

array([0.9062051 , 0.42270708, 0.61545878, 0.24109047, 0.82749608,
       0.84623245, 0.62939095, 0.81316846, 0.06261864, 0.42782285,
       0.15574646, 0.77664102, 0.12633989, 0.4058525 , 0.64165081])

## Arreglo de numeros aleatorios pero que se encuentren en un rango
### La funcion recibe como parametro 3 numeros enteros
#### Inicio del rango, Final del rango y longitud

In [11]:
np.random.randint(0, 9, 10)

array([5, 0, 0, 1, 0, 4, 6, 3, 8, 0])

## Numeros que tienen un rango de diferencia
### Estos numeros tienen en cuenta los numeros definidos (inicio y fin) y tienen una diferencia definida entre cada numero del arreglo

In [13]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])