# Clase numero 2
## Numpy & Pandas

In [2]:
import numpy as np

### H

In [4]:
a = np.random.randint(0, 100, 20)
a

array([30, 26, 59, 38, 46,  2, 45, 31, 18, 27, 44,  3,  8,  6, 98, 38, 59,
       86, 71, 90])

## Operaciones sobre matrices

In [8]:
A = a.reshape(5, 4)
A

array([[30, 26, 59, 38],
       [46,  2, 45, 31],
       [18, 27, 44,  3],
       [ 8,  6, 98, 38],
       [59, 86, 71, 90]])

In [9]:
A[0]

array([30, 26, 59, 38])

In [10]:
A[0].sum()

153

In [11]:
A[0].max()

59

In [12]:
A[0].min()

26

In [13]:
A[0].mean()

38.25

In [14]:
A[0].std()

12.735285626950029

### Suma de los valores mediante una transpuesta

In [15]:
A

array([[30, 26, 59, 38],
       [46,  2, 45, 31],
       [18, 27, 44,  3],
       [ 8,  6, 98, 38],
       [59, 86, 71, 90]])

In [17]:
A.T[2].sum()

317

### Toma todos los valores en la columna 2

In [18]:
A[:,2].sum()

317

### 

In [4]:
a = np.random.randint(0, 100, 200)
a

array([57, 20,  4, 80, 71, 35, 12, 59, 65, 84, 34, 88, 38, 47, 32, 42, 68,
       48, 44, 34, 32, 85, 39, 10, 67, 46, 53, 68,  2, 32, 18, 44, 63, 46,
       14, 71, 27, 53, 87, 39, 13, 21,  0, 12, 96, 34, 53, 87, 12, 84, 98,
       52, 69, 60, 63, 59, 40, 25, 75, 90, 72, 83, 66, 40, 74, 48, 15, 88,
       44, 44,  0,  7, 29, 59,  9, 25, 76, 25,  0, 34, 21, 23, 32, 12, 46,
       24, 74,  6, 88, 12, 49, 86, 43, 14, 49, 91, 21, 26, 88, 76, 14, 24,
       68, 99, 27, 77, 79, 49,  7, 75, 13, 46, 80, 27, 84,  0, 77, 66, 80,
       31, 98, 66, 73, 80, 37, 19, 56, 19, 17, 56, 86,  3, 79,  9,  9,  1,
       80, 18, 86, 91, 11, 64,  6, 60, 67, 38, 57, 98, 99, 70, 25, 56,  1,
       22, 47, 22, 54,  2, 38, 19, 53, 20, 84, 27, 57, 15, 40, 87, 95, 38,
       20, 27, 47, 97, 39, 87, 42,  0, 36, 94, 93, 44, 67, 57, 45,  8, 56,
       49, 22, 16,  4, 17, 58, 44, 17, 55, 99, 84, 86, 98])

In [ ]:
a