In [1]:
import numpy as np

In [2]:
a = np.random.randint(1, 5, 10)
a

array([4, 4, 2, 4, 1, 4, 3, 3, 2, 2])

In [3]:
b = np.random.randint(1, 5, 10)
b

array([2, 1, 4, 2, 1, 3, 1, 3, 3, 4])

In [5]:
# Comparar si los elementos son mayores al del arreglo anterior
a > b

array([ True,  True, False,  True, False,  True,  True, False, False,
       False])

In [7]:
# Mostrar donde los elementos coinciden en valor y posicion
a[a == b]

array([1, 3])