In [1]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b = a
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Al momento de igualar la variable, se hace referencia al mismo objeto en memoria pero con diferente etiqueta

In [5]:
b[0] = 69
a

array([69,  1,  2,  3,  4,  5,  6,  7,  8,  9])

### Se demuestra lo anterior mediante la identificacion de id de cada variable

In [6]:
id(a)

1822864480208

In [7]:
id(b)

1822864480208

# Vista
## Es el acceso de informacion a un arreglo, pero este si puede modificar los valores 

In [9]:
c = a.view()
c

array([69,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [10]:
c[2] = 200

In [11]:
c

array([ 69,   1, 200,   3,   4,   5,   6,   7,   8,   9])

In [12]:
a

array([ 69,   1, 200,   3,   4,   5,   6,   7,   8,   9])

## Podemos ver que informacion tiene cierto arreglo mediante FLAGS

In [13]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [14]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

## Si en algun momento deseamos cambiar los valores de un arreglo sin perder la informacion original. podemos crear una copia
### Asi la informacion sera propia y esta a su vez no afectara al arreglo base

In [17]:
e = a.copy()
e

array([ 69,   1, 200,   3,   4,   5,   6,   7,   8,   9])

In [18]:
# Agregamos un valor al arreglo secundario
e[0] = 88
e

array([ 88,   1, 200,   3,   4,   5,   6,   7,   8,   9])

In [19]:
# Mostramos los datos del arreglo base para comprobar que no se esta ocupando 
a

array([ 69,   1, 200,   3,   4,   5,   6,   7,   8,   9])