# Tipos de datos en numpy

![title](/mnt/c/Users/G/Z/python/analisis/numpy/tipos_de_datos_numpy.png)

# Obtener elementos de Numpy

In [15]:
import numpy as np

### Definimos el arreglo y lo almacenamos en una variable

In [16]:
a = np.array([10, 20, 30, 40, 50, 60])
a

array([10, 20, 30, 40, 50, 60])

### Al igual que una Lista o tupla, se pueden acceder a elementos mediante su posicion de arrelgo

In [17]:
a[0]

10

In [18]:
a[4]

50

### Usando los trucos, tambien podemos usar el -1 para obtener el ultimo elemento sin saber la longitud del arreglo

In [19]:
a[a.size -1]

60

## Podemos crear subarreglos a partir del arreglo original

In [20]:
a[1:4]

array([20, 30, 40])

In [21]:
a[1:6:2]

array([20, 40, 60])

Podemos invertir el orden del arreglo mediante los mismos metodos de la lista o tupla

In [22]:
a[::-1]

array([60, 50, 40, 30, 20, 10])

### Podemos realizar operacioines con los arreglos sin la necesidad de ocupar algun tipo de ciclo

Ejemplo con la lista nativa de python

In [23]:
lista = [0, 3, 4, 5]

In [24]:
for i in lista:
    print(a[i])

10
40
50
60


Ejemplo con numpy

In [25]:
a[lista]

array([10, 40, 50, 60])

podemos mostrar los datos segun su indice mediante un arreglo

In [26]:
a[[0,0,1,4,5]]

array([10, 10, 20, 50, 60])

### Podemos realizar operaciones sobre los elementos sin necesidad de ocupar ciclos

In [27]:
a * 10

array([100, 200, 300, 400, 500, 600])

Operacion por cada uno de los elementos de la lista

In [28]:
((a * 10) - 10) /2

array([ 45.,  95., 145., 195., 245., 295.])