# Ejecucion de funciones

In [4]:
import numpy as np


In [5]:
def simple_operation(val):
    return val * 10

In [6]:
a = np.random.randint(1, 10, 10)
a

array([7, 3, 5, 2, 4, 4, 1, 4, 5, 6])

### Usando la funcion directamente

In [7]:
simple_operation(a)

array([70, 30, 50, 20, 40, 40, 10, 40, 50, 60])

### Usandolo como metodo trandicional en listas python

In [8]:
for i in a:
    print(simple_operation(i))

70
30
50
20
40
40
10
40
50
60


### Vectorizando la funcion 

In [10]:
func_vect = np.vectorize(simple_operation)

In [11]:
func_vect(a)

array([70, 30, 50, 20, 40, 40, 10, 40, 50, 60])