# Matrices
## Arreglos multidimencionales

In [2]:
import numpy as np

### Crearemos una lista que a su vez recibe otra lista

In [3]:
a = np.array([[1, 2, 3, 4], [11, 22, 33, 44], [21, 22, 23, 24]])
a

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44],
       [21, 22, 23, 24]])

### Mostrar las dimensiones del arreglo

In [4]:
a.ndim

2

### Muestra la forma del arreglo

In [5]:
a.shape

(3, 4)

### Conocer la cantidad de elementos dentro de la matriz

In [6]:
a.size

12

### Obtener un valor accediendo mediante su ubicacion 

In [7]:
a[0][0]

1

Arreglo / X(0) / Y(0)

In [8]:
a[2][3]

24

In [9]:
a[2,3]

24

Obtener los valores que se encuentran en la fila n2, con el indice 1, 2 y 3

In [10]:
a

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44],
       [21, 22, 23, 24]])

In [14]:
a[1][1:4]

array([22, 33, 44])

In [15]:
a[1,1:4]

array([22, 33, 44])

Obtener los valores de un listado mediante su ubicacion

In [16]:
a[1, [0, 2, 3]]

array([11, 33, 44])

### Retornar el arreglo de una sola dimension [Vista compacta]

In [17]:
a.ravel()

array([ 1,  2,  3,  4, 11, 22, 33, 44, 21, 22, 23, 24])

### Retornar una copia de el arreglo original 

In [18]:
a.flatten()

array([ 1,  2,  3,  4, 11, 22, 33, 44, 21, 22, 23, 24])