# Operaciones basicas

In [2]:
import numpy as np
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Todas las operaciones no necesitan de ciclos para llevarse a cabo
### Podemos hacer operaciones directamente en el arreglo, pero estas no se guardara. Para ello se almacenan en variables distintas o sobre la que se llamo

In [3]:
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
b= a * 2
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Suma

In [7]:
a + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Resta

In [8]:
a - 3

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

### Multiplicacion

In [9]:
a * 8

array([ 8, 16, 24, 32, 40, 48, 56, 64, 72, 80])

### Division

In [10]:
a / 10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Operaciones con arreglos

## Sumar todos los elementos del arreglo

In [12]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
a.sum()

55

### Conocer el elemento mas pequeño dentro del arreglo

In [13]:
a.min()

1

### Conocer el elemento mas grande dentro del arreglo

In [14]:
a.max()

10

# Operaciones estadisticas

## Conocer la desviacion estandar del arreglo

In [15]:
a.std()

2.8722813232690143

## Conocer la media del arreglo

In [16]:
a.mean()

5.5

# Operaciones con matrices

### Matriz numero 1

In [17]:
A = np.random.randint(1, 10, 10)
A

array([2, 5, 1, 1, 6, 7, 6, 6, 1, 4])

In [19]:
A = A.reshape(2, 5)
A

array([[2, 5, 1, 1, 6],
       [7, 6, 6, 1, 4]])

### Matriz numero 2

In [20]:
B = np.random.randint(1, 10, 10).reshape(2, 5)
B

array([[7, 7, 2, 9, 6],
       [8, 1, 3, 4, 6]])

# ejemplo

In [21]:
A * B

array([[14, 35,  2,  9, 36],
       [56,  6, 18,  4, 24]])