# Operadores relacionales y logicos

In [2]:
import numpy as np
a =  np.random.randint(1, 10, 10)
a

array([4, 2, 4, 2, 6, 3, 3, 3, 8, 6])

### Valor menor que arreglo

In [3]:
a < 5

array([ True,  True,  True,  True, False,  True,  True,  True, False,
       False])

## Podemos mostrar en una sublista los valores que cumplen la condicion

In [4]:
a[a > 5]

array([6, 8, 6])

In [5]:
a[a < 5]

array([4, 2, 4, 2, 3, 3, 3])

## Implementando operadores logicos

In [7]:
c = np.random.randint(0, 100, 200)
c

array([27, 31,  9, 43, 86, 91, 29, 24, 79,  4, 31, 46, 38, 97, 54, 76,  8,
       78, 20, 87, 71, 32, 62, 12, 69, 79, 45, 71, 79, 42, 47, 45, 13, 78,
       28, 72,  3, 39, 10, 34, 90, 57, 72, 17,  2, 65, 17,  1, 94, 20, 63,
       62, 52, 98,  0, 89, 54, 53, 41, 83, 64, 10, 42, 59,  0, 55, 27, 22,
       17, 33, 77, 53, 71, 10, 88, 58, 52, 57,  5, 79, 67, 77, 16, 30, 85,
        9, 95, 25, 46, 61, 48, 60, 92,  3, 84, 62, 86, 42, 92, 67, 14, 45,
       37,  1, 44, 46, 67, 61,  8, 38, 33, 66, 19, 15, 89, 86, 74,  9, 43,
       10, 85, 58, 48, 27, 83, 80, 47, 92, 96, 43,  4, 46, 66, 52, 64, 91,
       51, 99, 52, 71, 42, 98, 81, 89, 52, 11, 41, 48, 54, 88, 28,  0, 96,
       51, 90, 86, 84, 71,  3, 32, 12, 13,  0, 90, 52, 33, 31, 11, 56, 58,
       80, 79, 57, 62, 72, 60, 96,  9, 67, 84, 30, 63, 58, 10, 35, 78, 86,
       74, 47, 76, 39,  2, 62, 48, 52, 22, 63, 99, 12, 82])

In [8]:
c[c > 10]

array([27, 31, 43, 86, 91, 29, 24, 79, 31, 46, 38, 97, 54, 76, 78, 20, 87,
       71, 32, 62, 12, 69, 79, 45, 71, 79, 42, 47, 45, 13, 78, 28, 72, 39,
       34, 90, 57, 72, 17, 65, 17, 94, 20, 63, 62, 52, 98, 89, 54, 53, 41,
       83, 64, 42, 59, 55, 27, 22, 17, 33, 77, 53, 71, 88, 58, 52, 57, 79,
       67, 77, 16, 30, 85, 95, 25, 46, 61, 48, 60, 92, 84, 62, 86, 42, 92,
       67, 14, 45, 37, 44, 46, 67, 61, 38, 33, 66, 19, 15, 89, 86, 74, 43,
       85, 58, 48, 27, 83, 80, 47, 92, 96, 43, 46, 66, 52, 64, 91, 51, 99,
       52, 71, 42, 98, 81, 89, 52, 11, 41, 48, 54, 88, 28, 96, 51, 90, 86,
       84, 71, 32, 12, 13, 90, 52, 33, 31, 11, 56, 58, 80, 79, 57, 62, 72,
       60, 96, 67, 84, 30, 63, 58, 35, 78, 86, 74, 47, 76, 39, 62, 48, 52,
       22, 63, 99, 12, 82])

In [9]:
# Mostrar cuantos elementos cumplen con la condicion
c[c > 10].size

175

## Mostrar los elementos que sean mayor de 10, pero menor que 50

In [10]:
c[(c > 10) & (c <50 )]

array([27, 31, 43, 29, 24, 31, 46, 38, 20, 32, 12, 45, 42, 47, 45, 13, 28,
       39, 34, 17, 17, 20, 41, 42, 27, 22, 17, 33, 16, 30, 25, 46, 48, 42,
       14, 45, 37, 44, 46, 38, 33, 19, 15, 43, 48, 27, 47, 43, 46, 42, 11,
       41, 48, 28, 32, 12, 13, 33, 31, 11, 30, 35, 47, 39, 48, 22, 12])

In [11]:
c[(c > 10) & (c <50 )].size

67

## Mostrando los elementos que no sean iguales a 10, pero que sean menores a 20

In [12]:
c[ (c != 10) & (c < 20)]

array([ 9,  4,  8, 12, 13,  3, 17,  2, 17,  1,  0,  0, 17,  5, 16,  9,  3,
       14,  1,  8, 19, 15,  9,  4, 11,  0,  3, 12, 13,  0, 11,  9,  2, 12])

## Mostrando los valores que sean 40 o mayores de 80

In [15]:
c[(c == 40) | (c > 80) ]

array([86, 91, 97, 87, 90, 94, 98, 89, 83, 88, 85, 95, 92, 84, 86, 92, 89,
       86, 85, 83, 92, 96, 91, 99, 98, 81, 89, 88, 96, 90, 86, 84, 90, 96,
       84, 86, 99, 82])