# Ordenamiento

In [1]:
import numpy as np
a = np.random.randint(1, 100, 50)
a

array([17, 19, 24,  2, 21, 82, 39, 41, 32, 82, 96, 86, 54, 74, 67, 71, 47,
       27, 42,  9, 93,  8, 93, 95, 63, 44, 98, 21, 46, 95, 84, 36, 89, 14,
       82, 98, 73, 80,  1, 50, 43, 11, 88, 61, 42, 29,  2, 74, 77, 39])

## Ordenar ascendente

In [3]:
a.sort()
a

array([ 1,  2,  2,  8,  9, 11, 14, 17, 19, 21, 21, 24, 27, 29, 32, 36, 39,
       39, 41, 42, 42, 43, 44, 46, 47, 50, 54, 61, 63, 67, 71, 73, 74, 74,
       77, 80, 82, 82, 82, 84, 86, 88, 89, 93, 93, 95, 95, 96, 98, 98])

## Ordenar Descendente


In [5]:
a[::-1]

array([98, 98, 96, 95, 95, 93, 93, 89, 88, 86, 84, 82, 82, 82, 80, 77, 74,
       74, 73, 71, 67, 63, 61, 54, 50, 47, 46, 44, 43, 42, 42, 41, 39, 39,
       36, 32, 29, 27, 24, 21, 21, 19, 17, 14, 11,  9,  8,  2,  2,  1])