# Tipos de datos en Numpy

![Title](numpy\tipos_de_datos_numpy.png)

## Importamos las librerias con las que vamos a trabajar

In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

### Podemos cambiar el tipo de dato del arreglo mediante el comando dtype

In [3]:
np.array([1, 2, 3, 4, 5], dtype='f')

array([1., 2., 3., 4., 5.], dtype=float32)

### De igual manera podemos convertirlo de manera extensa mediante el comando completo *(Se recomienda mas)*

In [4]:
np.array([1, 2, 3, 4, 5], dtype=np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

# Normalizando los datos de un arreglo mixto a *flotante* o *entero*

#### Arreglo que almacena todos los datos

In [5]:
np.array([1, 1.3, 2, 2.4, 3, 3.9, 4, 5, 6, 7.4, 8.0, 9.1])

array([1. , 1.3, 2. , 2.4, 3. , 3.9, 4. , 5. , 6. , 7.4, 8. , 9.1])

#### Arreglo que solo almacena los flotantes

In [6]:
np.array([1, 1.3, 2, 2.4, 3, 3.9, 4, 5, 6, 7.4, 8.0, 9.1], dtype=np.float32)

array([1. , 1.3, 2. , 2.4, 3. , 3.9, 4. , 5. , 6. , 7.4, 8. , 9.1],
      dtype=float32)

#### Arreglo que solo almacena los enteros

In [7]:
np.array([1, 1.3, 2, 2.4, 3, 3.9, 4, 5, 6, 7.4, 8.0, 9.1], dtype='i')

array([1, 1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

# Arreglo de *entero* a *booleano*

In [11]:
np.array([1, 0, 1, 0, 1, 1, 0], dtype=bool)

array([ True, False,  True, False,  True,  True, False])